#!/usr/bin/env bash

##########################
# IXNAY: A Saner Nix TUI #
##########################

# Nix has a terrible UI/UX, so...
# Note: May need to run as sudo for some ops. See note below.
# Second note: Now assumes flakes are enabled

#help Are you a Nix noob?
#help I have a possible solution! IXNAY! A sane wrapper for nix-shell, nix and friends, etc.
#help Configuration:
#help    Set IXNAY_MUTE_CMD_ECHO env variable to stop ixnay from printing out the
#help    underlying command it will run before it runs it.
#help    Set SWITCH_NOW env variable to switch to the new config now instead of requiring a reboot.
#help
#help Usage: ixnay <command> [<args>] [<options>]

ixnay() {
  # editing via "edit ixnay"
  [ -n "${EDIT}" ] && unset EDIT && edit_function "${FUNCNAME[0]}" "$BASH_SOURCE" && return
  # ANSI coloring
  # Color constants
  local ANSI="\033["
  # local TXTRED='0;31m' # Red
  local TXTYLW='0;33m' # Yellow
  # local TXTGRN='0;32m' # Green
  local TXTRST='0m'    # Text Reset, disable coloring
  function echo_yellow() {
    echo -e "${ANSI}${TXTYLW}${1}${ANSI}${TXTRST}" >&2
  }
  AWK=$(command -v gawk || command -v awk)
  # if the path leads to awk instead of gawk, we warn the user
  if [ "$(basename "$AWK")" = "awk" ]; then
    echo_yellow "Warning: Using 'awk' instead of 'gawk'. Some features may not work as expected. Highly recommend installing 'gawk' instead."
  fi
  # distro detection
  function distro() {
    $AWK -F'=' '/^NAME=/{gsub(/"/, "", $2); print $2}' ${1:-/etc/os-release}
  }
  if [ "$(uname)" = "Darwin" ]; then
    DISTRO="macos"
  else # assume linux
    # shellcheck disable=SC2034
    DISTRO=$(distro)
    # this downcase requires bash 4+; you can pipe to tr '[:upper:]' '[:lower:]' instead
    DISTRO="${DISTRO,,}"
  fi
  # graceful dependency enforcement
  # Usage: needs <executable> [provided by <packagename> or explain how to get it here]
  function needs() {
    local bin=$1
    shift
    # shellcheck disable=SC2086
    command -v $bin >/dev/null 2>&1 || { echo >&2 "I require $bin but it's not installed or in PATH; $*"; return 1; }
  }
  # datetimestamp of a file
  function datetimestampfile() {
    stat -c '%y' "$1" | $AWK '{print $1$2}' | tr -d ':-' # | cut -d"." -f1 # to remove milliseconds
  }
  # log location
  local XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
  local IXNAY_LOGFILEDIR="${IXNAY_LOGFILEDIR:-$XDG_CACHE_HOME/ixnay}"
  local LOGFILE="$IXNAY_LOGFILEDIR/last_reify.log"
  local SWITCH_OR_BOOT
  [ -n "${SWITCH_NOW}" ] && SWITCH_OR_BOOT="switch" || SWITCH_OR_BOOT="boot"
  function _ixnay_help() {
    # this is some cleverness that extracts the inline help text from all the case options
    $AWK '
      BEGIN {
        if (!("platform" in PROCINFO)) {
          print "Please run this script with GNU awk (gawk) earliest in your PATH.";
          exit 1
        }
      }
      /^\x20*#help / {
        sub(/^\x20+/, "", $0)
        print substr($0, 7)
        next
      }
      /#nodoc$/ { next }
      /^\x20+(""|\*|(-?\\?[a-zA-Z\?]|(--)?[a-zA-Z0-9\-_]{2,})(\x20\|\x20(-?\\?[a-zA-Z\?]|(--)?[a-zA-Z0-9\-_]{2,}))*\x20?)\)/ {
        sub(/^\x20+/,"", $0)
        sub(/^\*\)/,"<arg>", $0)
        sub(/^""/,"", $0)
        sub(/\)\x20+#args\x20+/," ", $0)
        sub(/\)\x20+#.*$/,"", $0)
        sub(/\)\x20*$/,"", $0)
        sub(/^\x20*/,"", $0)
        print ""
        print "ixnay " $0
      }
    ' "$0"
  }
  local NIX_COMMAND=${NIX_COMMAND:-nix}
  case $NIX_COMMAND in
    nix-env) #nodoc
      needs nix-env it comes as part of nix
      needs nix-channel it comes as part of nix
      needs nix-store it comes as part of nix
      ;;
    nix) #nodoc
      needs nix "it comes as part of nix with the \"experimental\" flakes configuration turned on"
      ;;
  esac
  case $1 in
    help | --help | -h | -?)
      #help -- The help you see here!
      _ixnay_help
      return 0
      ;;
    channels)
      #help -- Lists nix channels. Lists global channels if sudo'd in a multiuser setup.
      #help    NOTE: Using Flakes instead of channels is advised.
      echo_yellow "NOTE: Using Flakes instead of channels is advised."
      [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "nix-channel --list"
      if [ -n "${DRY_RUN}" ]; then
        return 0
      fi
      nix-channel --list
      ;;
    add-channel | add) #args <channelname> <url>
      #help -- Adds channel <channelname> via <url>.
      #help    NOTE: Using Flakes instead of channels is advised.
      echo_yellow "NOTE: Using Flakes instead of channels is advised."
      shift;
      [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "nix-channel --add \"$2\" \"$1\""
      if [ -n "${DRY_RUN}" ]; then
        return 0
      fi
      nix-channel --add "$2" "$1"
      ;;
    remove-channel | remove) #args <channelname>
      #help -- Removes channel <channelname>.
      #help    NOTE: Using Flakes instead of channels is advised.
      echo_yellow "NOTE: Using Flakes instead of channels is advised."
      shift;
      [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "nix-channel --remove \"$1\""
      if [ -n "${DRY_RUN}" ]; then
        return 0
      fi
      nix-channel --remove "$1"
      ;;
    sync) #args <channelname>
      #help -- Updates channel <channelname> from the Internet; leave blank for all
      #help -- You may need to sudo this to update global channels (such as on NixOS).
      #help    NOTE: Using Flakes instead of channels is advised.
      echo_yellow "NOTE: Using Flakes instead of channels is advised."
      shift;
      [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "nix-channel --update $1"
      if [ -n "${DRY_RUN}" ]; then
        return 0
      fi
      # shellcheck disable=SC2086
      nix-channel --update $1
      ;;
    reify | realize | apply | rebuild) #args [no-upgrade | no-update | no-up | --no-up | --no-upgrade | --no-update | here]
      #help -- Reads the config files, sets up the new config, switches to the new config, optionally doesn't update from the Internet.
      #help -- Also logs its output to IXNAY_LOGFILEDIR (defaults to $XDG_CACHE_HOME/ixnay), rotating it with a datetimestamp,
      #help -- and then displays it.
      #help -- NixOS required currently. May work with nix-darwin in the future.
      #help -- (The "here" arg is a synonym for the other "no-upgrade" options.)
      if [ "$DISTRO" = "nixos" ]; then
        # rename the last logfile to its timestamp
        if [ -f "$LOGFILE" ]; then
          local LOGFILE_TIMESTAMP=$(datetimestampfile "$LOGFILE")
          mv "$LOGFILE" "$IXNAY_LOGFILEDIR/${LOGFILE_TIMESTAMP}_reify.log"
        else
          mkdir -p "$IXNAY_LOGFILEDIR"
        fi
        shift;
        case $1 in
          no-upgrade | no-update | no-up | --no-up | --no-upgrade | --no-update | here) #nodoc
            [ "$IXNAY_MUTE_CMD_ECHO" ] || echo_yellow "sudo nixos-rebuild $SWITCH_OR_BOOT 2>&1 | tee \"$LOGFILE\""
            sudo nixos-rebuild $SWITCH_OR_BOOT 2>&1 | tee "$LOGFILE"
            local retcode=$?
            cat "$LOGFILE"
            return $retcode
            ;;
          *) #nodoc
            [ "$IXNAY_MUTE_CMD_ECHO" ] || echo_yellow "sudo nixos-rebuild $SWITCH_OR_BOOT --upgrade 2>&1 | tee \"$LOGFILE\""
            sudo nixos-rebuild $SWITCH_OR_BOOT --upgrade 2>&1 | tee "$LOGFILE"
            local retcode=$?
            cat "$LOGFILE"
            return $retcode
            ;;
        esac
      else
        echo_yellow "This command applies an entire system configuration and thus requires NixOS. https://nixos.org/"
        echo_yellow "(nix-darwin exists for macOS, but is not supported by ixnay yet.)"
        return 2
      fi
      ;;
    see | try) #args <packagename> [run [<execname> [<args>]]]
      #help -- Downloads and installs a package, optionally runs it, optionally with a different name
      #help    (defaults to the same name as the package), optionally with arguments. Makes it available
      #help    in your shell by modifying PATH.
      #help    Some 'see' usage examples:
      #help    ixnay see mop run # downloads, installs and runs mop. assumes package & executable name are identical
      #help    ixnay see mop # downloads and installs mop and makes it available in your shell
      #help    ixnay try mop # downloads & installs mop package temporarily
      #help    ixnay see mop run mopper [<args>] # downloads & installs mop package, but runs it with a different name and args
      shift;
      case $2 in
        run) #nodoc
          case $3 in
            "") #nodoc
              [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "nix-shell -p $1 --run $1"
              if [ -n "${DRY_RUN}" ]; then
                return 0
              fi
              # shellcheck disable=SC2086
              nix-shell -p $1 --run $1
              ;;
            *) #nodoc
              local app="$1"
              shift; shift;
              [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "nix-shell -p $app --run \"$*\""
              if [ -n "${DRY_RUN}" ]; then
                return 0
              fi
              # shellcheck disable=SC2086
              nix-shell -p $app --run "$*"
              ;;
          esac
          ;;
        *) #nodoc
          [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "nix-shell -p $1"
          # shellcheck disable=SC2086
          nix-shell -p $1
          ;;
      esac
      ;;
    install | i) #args [<repo>#]<packagename>
        #help -- Imperatively installs a package into your profile.
        #help    If no repo name is specified, default to nixpkgs.
        #help    Note: This is not a recommended use of NixOS because it is not declarative,
        #help    but it works for people new to Nix or using the nix overlay install method,
        #help    and it will be preserved from being garbage-collected (but you will lose it
        #help    if your system dies and you neither have a backup nor have it declaratively
        #help    named in a configuration file you source-control... which is why the former
        #help    is recommended!)
      if [ -n "${NIXOS}" ]; then
        echo_yellow "Note: Since you're on NixOS, is recommended to add a package to your global 'packages' config declaratively,"
        echo_yellow "instead of installing it into your profile."
      fi
      case $2 in
        "")
          # warn about the lack of an argument
          echo_yellow "Warning: No package specified for installation."
          echo_yellow "Usage: ixnay install <packagename>"
          return 1
          ;;
        unstable) #nodoc
          shift;
          IFS="#" read -r chan pack <<< "$2"
          # if the string is blank
          if [ -z "$pack" ]; then
            # no channel specified; use default
            pack="$chan"
            chan="github:nixos/nixpkgs/nixos-unstable"
          fi
          [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "$NIX_COMMAND profile install ${chan}#${pack}"
          if [ -n "${DRY_RUN}" ]; then
            return 0
          fi
          # shellcheck disable=SC2086
          $NIX_COMMAND profile install ${chan}#${pack}
          ;;
        *) #nodoc
          shift;
          IFS="#" read -r chan pack <<< "$1"
          # if the string is blank
          if [ -z "$pack" ]; then
            # no channel specified; use default
            pack="$chan"
            chan="nixpkgs"
          fi
          [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "$NIX_COMMAND profile install ${chan}#${pack}"
          if [ -n "${DRY_RUN}" ]; then
            return 0
          fi
          # shellcheck disable=SC2086
          $NIX_COMMAND profile install ${chan}#${pack}
          ;;
      esac
      ;;
    uninstall | un) #args <packagename>
      #help -- Imperatively uninstalls a package from your profile.
      #help    See the caveats/suggestions for "ixnay install".
      if [ -n "${NIXOS}" ]; then
        echo_yellow "Note: Since you're on NixOS, is recommended to remove a package from your global 'packages' config declaratively,"
        echo_yellow "instead of uninstalling it from your profile."
      fi
      shift;
      local package=$1
      # Use awk to find all profile numbers with the given package name
      # shellcheck disable=SC2155
      [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "$NIX_COMMAND profile list | $AWK -v package=\"$package\" '
          BEGIN { RS=\"\\\n\\\n\"; FS=\"(\\\n|: +)\"; }
          \$4 ~ package \"\$\" { printf \"%s\\\n\", \$2; }
      '"
      local profile_numbers=$($NIX_COMMAND profile list | $AWK -v package="$package" '
          BEGIN { RS="\n\n"; FS="(\n|: +)"; }
          $4 ~ package "$" { printf "%s\n", $2; }
      ')
      # Check if any profile numbers were found
      if [ -z "$profile_numbers" ]; then
          echo "Package not found in the profile list: $package"
          return 1
      fi
      # Run the desired nix profile action for each found profile number
      for profile_number in $profile_numbers; do
        [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "nix profile remove $profile_number"
        if [ -n "${DRY_RUN}" ]; then
          break
        fi
        # shellcheck disable=SC2048,SC2086
        nix profile remove $profile_number
      done
      ;;
    update | u)
      #help -- Updates your channel(s) from the Internet.
      #help    NOTE: Using Flakes instead of channels is advised.
      echo_yellow "NOTE: Using Flakes instead of channels is advised."
      [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "sudo nix-channel --update"
      if [ -n "${DRY_RUN}" ]; then
        return 0
      fi
      sudo nix-channel --update
      ;;
    upgrade | up) #args [<packagename>[ <packagename>]* | nix]
      #help -- Imperatively upgrades a package(s) in your profile.
      #help    Or Nix itself if you specify 'nix' by itself.
      #help    Or all Nix profile-installed packages if none specified, or if you specify '--all'.
      shift;
      local packages="$*"
      # set packages to "--all" if it is empty
      [ -z "$packages" ] && packages="--all"
      [ -v DEBUG ] && echo_yellow "DEBUG: packages is $packages"
      case $packages in
        nix) #nodoc
          # [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "nix-channel --update"
          # nix-channel --update
          # OK so it turns out that "nix upgrade-nix" is currently broken
          # so we will use a workaround just for this case
          # [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "nix upgrade-nix"
          # nix upgrade-nix
          # Record path to nix executable.
          
          # Using this hosed my Nix install due to having used the Determinate Nix Installer,
          # which I had forgotten, so for now I will just warn about its existence
          # and to follow its own instructions for upgrading Nix itself.
          # (The original code that was here was deleted.)
          if [ -f "/nix/receipt.json" ]; then
            echo_yellow "Warning: You have used the Determinate Nix Installer. Please follow its instructions for upgrading Nix itself."
            echo_yellow "You can find it at https://github.com/DeterminateSystems/nix-installer"
            echo_yellow "This is likely \"sudo -i nix upgrade-nix\", but may have changed."
            echo_yellow "The receipt file, which it uses to uninstall, is located at /nix/receipt.json"
          fi
          ;;
        *) #nodoc
          # If the list of arguments contains "nix", remove it and warn the user about having to do it separately.
          if [[ "$packages" =~ (^|[[:space:]])nix($|[[:space:]]) ]]; then
            echo_yellow "Warning: You have specified 'nix' for upgrading. This must be done separately."
            echo_yellow "Removing it from the list of packages to upgrade for now."
            # Remove "nix" from the list of packages to upgrade.
            packages=$(echo "$packages" | sed -E 's/(^|[[:space:]])nix($|[[:space:]])/ /g')
          fi
          [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "nix profile upgrade $packages"
          if [ -n "${DRY_RUN}" ]; then
            return 0
          fi
          # shellcheck disable=SC2048,SC2086
          nix profile upgrade $packages
          ;;
      esac
      ;;
    wipe-history)
      #help -- Wipes the non-current history of your profile(s).
      [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "$NIX_COMMAND profile wipe-history"
      if [ -n "${DRY_RUN}" ]; then
        return 0
      fi
      $NIX_COMMAND profile wipe-history
      ;;
    history)
      #help -- Shows the history of your profile(s).
      [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "$NIX_COMMAND profile history"
      if [ -n "${DRY_RUN}" ]; then
        return 0
      fi
      $NIX_COMMAND profile history
      ;;
    rollback | rb)
      #help -- Rolls back your profile(s) to the previous generation.
      #help    (Undoes the last profile change.)
      [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "$NIX_COMMAND profile rollback"
      if [ -n "${DRY_RUN}" ]; then
        return 0
      fi
      $NIX_COMMAND profile rollback
      ;;
    list | l)
      #help -- List local explicitly-installed packages
      # Use awk to find all packages from the profile list
      # shellcheck disable=SC2155
      local packages=$($NIX_COMMAND profile list | $AWK -F. '
        /Flake attribute:/{ print $NF }
      ')
      # Check if any profile numbers were found
      if [ -z "$packages" ]; then
        echo "There are no profile packages installed."
      else
        echo "### Profile packages ###"
        # Print the packages, sorted and uniquified
        echo -e "$packages" | tr ' ' '\n' | sort -u
      fi
      echo
      echo "### System packages ###"
      # this is a bit of a wonky way to get at this data, but it seems to work at least
      # check for running on nixos; otherwise there are no system packages and we error
      if [ "$DISTRO" = "nixos" ]; then
        nix-store -q --tree /run/current-system | rg '^│   [├└]───' | $AWK -F/ '{ print $4 }' | $AWK -F' ' '{ print $1 }' | cut -c34- | sort -u
      else
        echo_yellow "There are no system packages installed since this isn't NixOS."
      fi
      ;;
    locate | find | f) #args <packagename>
      #help -- Locate an available package. It will return any names and versions
      #help    across all defined channels, or suggest possibilities if spelled wrong or incomplete.
      #help    May take a while to complete because nix-env is kind of a slow hacky mess.
      #help    NOTE: This uses nix-env and channels, which are essentially deprecated currently;
      #help          it is suggested to use "search" instead.
      shift;
      [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "nix-env -qaP $*"
      if [ -n "${DRY_RUN}" ]; then
        return 0
      fi
      # shellcheck disable=SC2048,SC2086
      nix-env -qaP $*
      if [ $? -ne 0 ]; then
        echo_yellow "I see it errored. Locate/find not really recommended anymore. Try \`ixnay search\` instead."
      fi
      ;;
    search | s | query | q) #args <name_or_regex> [<name_or_regex> ...]
      #help -- Searches all available packages, and their descriptions, in nixpkgs (downloading its DB first,
      #help    if necessary) for a pattern, which may be a regex. Multiple patterns are AND'ed.
      #help    This uses "nix search" instead of nix-env.
      shift;
      [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "nix search nixpkgs $*"
      if [ -n "${DRY_RUN}" ]; then
        return 0
      fi
      # shellcheck disable=SC2048,SC2086
      nix search nixpkgs $*
      ;;
    optimize | optimise)
      #help -- Replaces any duplicate files in the Nix store with hardlinks, saving space.
      #help    Note that you can probably set this up to be done on a schedule via a config file option.
      [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "nix store optimise"
      if [ -n "${DRY_RUN}" ]; then
        return 0
      fi
      nix store optimise
      ;;
    clean | c | gc | garbage-collect | collect-garbage | purge)
      #help -- Delete all unreachable paths in the Nix store (anything that nothing active
      #help    is currently referencing), freeing up space.
      #help    Note that this should not include packages installed into a profile.
      [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "nix-collect-garbage"
      if [ -n "${DRY_RUN}" ]; then
        return 0
      fi
      nix-collect-garbage
      ;;
    validate | valid | check | verify)
      #help -- Validates the current contents of the Nix store.
      [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "nix-store --verify --check-contents"
      if [ -n "${DRY_RUN}" ]; then
        return 0
      fi
      nix-store --verify --check-contents
      ;;
    deps | dependencies) #args <packagename>
      #help -- Lists all the dependencies of a package.
      shift;
      [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "nix-store -q --references `which $1`"
      # nix-instantiate --eval --expr 'builtins.toJSON (import <nixos/nixos> {}).options.environment.systemPackages.definitionsWithLocations' --json | jq 'fromjson' -C
      if [ -n "${DRY_RUN}" ]; then
        return 0
      fi
      # shellcheck disable=SC2048,SC2086
      nix-store -q --references `which $1`
      ;;
    depends-on) #args <packagename>
      #help -- Lists all the packages/derivations that depend on a package.
      shift;
      [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "nix-store -q --referrers `which $1`"
      if [ -n "${DRY_RUN}" ]; then
        return 0
      fi
      # shellcheck disable=SC2048,SC2086
      nix-store -q --referrers `which $1`
      ;;
    repair | doc | doctor)
      #help -- Validates AND repairs the current contents of the Nix store.
      #help    Also ensures you are using flakes if you are using nix profiles.
      # verify nix profiles are configured to use flakes
      if [ -z "$NIX_PROFILES" ]; then
        echo "NIX_PROFILES is not set. Please set it to the right paths if you are using nix profiles."
        echo "It is typically set to the following value, so setting it to this in your dotfiles may fix this:"
        # echo "I will set it here temporarily:"
        echo_yellow "export NIX_PROFILES=\"/nix/var/nix/profiles/default $HOME/.nix-profile\""
        # export NIX_PROFILES="/nix/var/nix/profiles/default /Users/$USER/.nix-profile"
      fi
      # confirm that ~/.config/nix/nix.conf exists and contains flakes
      if [ ! -f "$HOME/.config/nix/nix.conf" ]; then
        echo "nix.conf does not exist. Please create it and add the following line to it:"
        echo "experimental-features = nix-command flakes"
        echo "You can do this by running the following command:"
        echo_yellow "mkdir -p $HOME/.config/nix && echo \"experimental-features = nix-command flakes\" > $HOME/.config/nix/nix.conf"
        # mkdir -p "$HOME/.config/nix" && echo "experimental-features = nix-command flakes" > "$HOME/.config/nix/nix.conf"
      else
        if ! grep -q "experimental-features = nix-command flakes" "$HOME/.config/nix/nix.conf"; then
          echo "nix.conf exists but does not contain the flakes experimental feature. Please add the following line to it:"
          echo "experimental-features = nix-command flakes"
          echo "You can do this by running the following command:"
          echo_yellow "echo \"experimental-features = nix-command flakes\" >> $HOME/.config/nix/nix.conf"
          # echo "experimental-features = nix-command flakes" >> "$HOME/.config/nix/nix.conf"
        fi
      fi
      [ -n "${IXNAY_MUTE_CMD_ECHO}" ] || echo_yellow "sudo -H nix-store --verify --check-contents --repair"
      sudo -H nix-store --verify --check-contents --repair
      ;;
    "") #args [<nothing, or anything not understood>]
      #help -- Prints this help message but returns 2 for bad usage
      _ixnay_help
      return 2
      ;;
  esac
}

# run the function, passing along any args, if this file was run directly (such as via sudo) instead of as an include
# sometimes, $0 contains a leading dash to indicate an interactive (or is it login?) shell,
# which is apparently an old convention (which also broke the basename call on OS X)
me=$(basename "${0##\-}")
if [ "$me" = "ixnay" ]; then
  # shellcheck disable=SC2048,SC2086
  ixnay $*
fi
